#!/usr/bin/env bash

# Usage: Merge the patches from all of your branches, after properly applying them.

# add items to the excluded_branches array to exclude them from being merged into master

excluded_branches=(
  "patch1"
  "patch2"
)

arrayContainsElement () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

make clean && rm -f config.h && git reset --hard forked/master &&
for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f3); do
	if [ "$branch" != "master" ];then
        arrayContainsElement "$branch" "${excluded_branches[@]}"
        if [ $? -eq 1 ]; then
            echo "************ Merging $branch ************"
		    git merge $branch -m $branch
        fi
	fi
done
make && sudo make clean install
