#!/usr/bin/env bash

# Usage: Merge the patches from all of your branches, after properly applying them.

# add items to the excluded_branches array to exclude them from being merged into master

excluded_branches=(
  "patch1"
  "patch2"
)

arrayContainsElement () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

failure_flag=0

make clean && rm -f config.h && git reset --hard forked/master &&
for branch in $(git branch --no-merged | tr -d '[:blank:]'); do
	if [ "$branch" != "master" ];then
        arrayContainsElement "$branch" "${excluded_branches[@]}"
        if [ $? -eq 1 ]; then
            echo "************ Merging $branch ************"
		    git merge $branch -m $branch
            if [ $? -ne 0 ];then
                failure_flag=1
            fi
        fi
	fi
done

if [ $failure_flag -eq 0 ];then
    make && sudo make clean install
fi

